#!/bin/sh -eu
#
# checkarray -- initiates a check run of an array's parity information.
#
# Copyright © 2006 martin f. krafft <madduck@debian.org>
# distributed under the terms of the Artistic Licence.
#
REVISION=2006.08.01.1621

PROGNAME=${0##*/}

about()
{
  echo "$PROGNAME -- RAID parity checker tool (revision $REVISION)"
  echo "Copyright © 2006 martin f. krafft <madduck@debian.org>"
  echo "Released under the terms of the Artistic Licence."
}

usage()
{
  about
  echo
  echo "Usage: $PROGNAME [options] [arrays]"
  echo
  echo "Valid options are:"
  cat <<-_eof | column -s\& -t
	-a|--all & check all assembled arrays (check /proc/mdstat).
	-c|--cron & honour setting AUTOCHECK in /etc/default/mdadm.
	-q|--quiet & suppress informational messages.
	-Q|--real-quiet & suppress all output messages, including warnings and errors.
	-h|--help & show this output.
	-V|--version & show version information.
	_eof
  echo
  echo "Examples:"
  echo "  $PROGNAME --all"
  echo "  $PROGNAME /dev/md[123]"
  echo
  echo "Devices can be specified in almost any format. The following are"
  echo "all equivalent:"
  echo "  /dev/md0, md0, /dev/md/0, /sys/block/md0"
  echo
  echo "The --all option overrides all arrays passed to the script."
  echo
  echo "You can control the status of a check with /proc/mdstat ."
}

SHORTOPTS=achVqQ
LONGOPTS=all,cron,help,version,quiet,real-quiet

eval set -- $(getopt -o $SHORTOPTS -l $LONGOPTS -n $PROGNAME -- "$@")

arrays=''
cron=0
all=0
quiet=0

for opt in $@; do
  case "$opt" in
    -a|--all) all=1;;
    -c|--cron) cron=1;;
    -h|--help) usage; exit 0;;
    -q|--quiet) quiet=1;;
    -Q|--real-quiet) quiet=2;;
    -V|--version) about; exit 0;;
    /dev/md/*|md/*) arrays="${arrays:+$arrays }md${opt#*md/}";;
    /dev/md*|md*) arrays="${arrays:+$arrays }${opt#/dev/}";;
    /sys/block/md*) arrays="${arrays:+$arrays }${opt#/sys/block/}";;
    --) :;;
    *) echo "$PROGNAME: E: invalid option: $opt" >&2; usage >&2; exit0;;
  esac
done

is_true()
{
  case "${1:-}" in
    [Yy]es|[Yy]|1|[Tt]rue|[Tt]) return 0;;
    *) return 1;
  esac
}

DEBIANCONFIG=/etc/default/mdadm
[ -f $DEBIANCONFIG ] && . $DEBIANCONFIG
if [ $cron = 1 ] && ! is_true ${AUTOCHECK:-false}; then
  [ $quiet -lt 1 ] && echo "$PROGNAME: I: disabled in $DEBIANCONFIG ." >&2
  exit 0
fi

if [ ! -f /proc/mdstat ]; then
  [ $quiet -lt 2 ] && echo "$PROGNAME: E: RAID subsystem not loaded, or /proc unavailable." >&2
  exit 2
fi

if [ -z "$(ls /sys/block/md* 2>/dev/null)" ]; then
  [ $quiet -lt 2 ] && echo "$PROGNAME: W: no active RAID arrays found." >&2
  [ $quiet -lt 2 ] && echo "$PROGNAME: W: (maybe uninstall the mdadm package?)" >&2
  exit 5
fi

if [ -z "$(ls /sys/block/md*/md/level 2>/dev/null)" ]; then
  [ $quiet -lt 2 ] && echo "$PROGNAME: W: kernel too old, no support for parity checks." >&2
  exit 6
fi

if ! egrep -q '^raid([1456]|10)$' /sys/block/md*/md/level 2>/dev/null; then
  [ $quiet -lt 1 ] && echo "$PROGNAME: I: no redundant arrays present; skipping checks..." >&2
  exit 0
fi

if [ -z "$(ls /sys/block/md*/md/sync_action 2>/dev/null)" ]; then
  [ $quiet -lt 2 ] && echo "$PROGNAME: W: no kernel support for parity checks." >&2
  exit 3
fi

[ $all = 1 ] && arrays="$(ls -d1 /sys/block/md* | cut -d/ -f4)"

for array in $arrays; do
  SYNC_ACTION_CTL=/sys/block/$array/md/sync_action

  if [ ! -e $SYNC_ACTION_CTL ]; then
    [ $quiet -lt 1 ] && echo "$PROGNAME: I: skipping non-redundant array $array." >&2
    continue
  fi

  if [ ! -w $SYNC_ACTION_CTL ]; then
    [ $quiet -lt 2 ] && echo "$PROGNAME: E: $SYNC_ACTION_CTL not writeable." >&2
    exit 4
  fi

  if [ "$(cat $SYNC_ACTION_CTL)" != idle ]; then
    [ $quiet -lt 2 ] && echo "$PROGNAME: W: array $array not idle, skipping..." >&2
    continue
  fi

  # run check for the array. The kernel will make sure that these requests
  # are properly queued so as to not kill one of the array.
  echo check > $SYNC_ACTION_CTL
  [ $quiet -lt 1 ] && echo "$PROGNAME: I: check queued for array $array." >&2
  
done

exit 0
