.\"
.\" This man page writeen aug 13 3004 by Robert Collins <robertc@robertcollins.net>
.\" This template provided by Tom Christiansen <tchrist@jhereg.perl.com>.
.\" 
.TH MDRUN 8 
.SH NAME
mdrun \- autodetect and activate all raid partitions
.SH SYNOPSIS
mdrun detects all (or named) raid partitions and activates them.

Without arguments: autodetect all RAID partitions and activate MDs.
.PP
.B mdrun
.B LIST
.PP
.B mdrun
[
.I DEVDIR
]
.I NUMBER UUID
[
.I NUMBER UUID ...
]
.SH WARNING
mdrun has been deprecated on Debian. Please use
.B mdadm
instead. You can find information on how to use and configure
.B mdadm
in the 
.BR mdadm(8)
and
.BR mdadm.conf(5)
manpages
.SH OPTIONS
.TP
.B LIST
lists all raids in the syntax needed for the number uuid pairs the alternative syntax accepts.
.TP
.I DEVDIR
An optional override for the /dev directory.
.TP
.I NUMBER UUID
pairs of number, uuids that define a md element to run. number comes from /dev/md/*.
.SH "RETURN VALUE"
Nothing is displayed and mdrun returns 0 on success.
.SH ERRORS
On error, non-zero is returned, and a diagnostic string is printed.
.SH EXAMPLES
mdrun.
.SH ENVIRONMENT
MORERAIDVOLUMES (list of strings) : additional raid disks to scan, eg. loop devices.
.SH NOTES
If the first argument is a directory, it will be used as a writeable temporary directory for device nodes. 
mdrun needs mknod to create them on-the-fly.
.SH CAVEATS
Create /dev/fs directory if you have devfs support in the kernel but do not want to mount it over /dev.
Usage of /dev/fs directory will keep mdrun away from /dev.
.SH AUTHOR
Eduard Bloch <blade@debian.org>.
.SH HISTORY
This man page was created Aug 13 2004 by Robert Collins.
.SH "SEE ALSO"
.BR mdadm (8).


